### ISSUE TITLE
Outdated script?

### ISSUE THREAD

**Issue by forenta** [aethelberht/letterboxd2imdb#1]
Has anyone been able to use that app these days? Maybe it's not working with letterboxd-csvs these days.
`requests.exceptions.MissingSchema: Invalid URL '2020-09-18': No schema supplied. Perhaps you meant http://2020-09-18?`

**Comment by aethelberht** [comment]
Updated to support latest letterboxd/imdb csv schema. Dropped OMDb support in favor of imdbpy.
