### ISSUE TITLE
Script crashes when the movie title contains commas

### ISSUE THREAD

**Issue by byteshaman** [aethelberht/letterboxd2imdb#2]
I don't know if the problem is only for the commas, I noticed that the film will be surrounded by " " (in the csv file) when it contains commas, and the script crashes. I solved this by searching and replacing all those characters with Excel as temporary solution.

I'm attaching my ratings.csv so that you can try to see what causes the problem :)
[ratings.zip](https://github.com/aethelberht/letterboxd2imdb/files/5978188/ratings.zip)

**Comment by aethelberht** [comment]
Problematic entry was Boss Level (2021), because it was so new that it lacked vote data. The script should work as-is because the film entry now has vote data on IMDb, but I've also added a safeguard against this issue in the future.
